project:
  type: website
  output-dir: docs

website:
  title: "Maxwell Pepperdine"
  favicon: images/my-favicon.png
  navbar:
    logo: images/my-favicon.png
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts.qmd
        text: Portfolio
      - text: Resume
        href: Resume/Living Resume.pdf
  page-footer:
    background: light
    left: Copyright 2024, Maxwell Pepperdine
    right: This website is built with {{< fa brands github title="the octocat guthub icon" >}}

format:
  html:
    theme: styles.scss
    mainfont: Nunito
    toc: false
    page-layout: full

editor: visual

